--PART 1 SELECT TO SHOW TABLE AND CONTENTS
SELECT SONG_ID, GENRE, SONG_NAME, SONG_DURATION, FIRST_PLAY, TIME_ADDED, ARTIST, ALBUM, PRICE FROM MUSIC ORDER BY SONG_ID;

--PART 1 CREATE
CREATE TABLE MUSIC (
    SONG_ID VARCHAR(20) PRIMARY KEY,
    GENRE VARCHAR(20) NOT NULL,
    SONG_NAME VARCHAR(20) NOT NULL,
    SONG_DURATION FLOAT(38) NOT NULL,
    FIRST_PLAY DATE NOT NULL,
    TIME_ADDED TIMESTAMP NOT NULL,
    ARTIST VARCHAR(20) NOT NULL,
    ALBUM VARCHAR(20) NULL,
    PRICE FLOAT(38) NULL    
);

--PART 1 INSERT
INSERT INTO MUSIC VALUES (
    'AB123',
    'POP',
    'GIANT',
    5.45,
    '13-MAR-19',
    CURRENT_TIMESTAMP,
    'CALVIN HARRIS',
    'EDM',
    5.45
);

INSERT INTO MUSIC VALUES (
    'CD123',
    'ROCK',
    'WOW',
    3.32,
    '17-MAR-19',
    CURRENT_TIMESTAMP,
    'POST MALONE',
    'BENTLEYS',
    6.50
);

INSERT INTO MUSIC VALUES (
    'EF123',
    'HIP HOP',
    'GOING BAD',
    5.55,
    '06-FEB-19',
    CURRENT_TIMESTAMP,
    'MEEK MILL',
    NULL,
    NULL
);

INSERT INTO MUSIC VALUES (
    'GH123',
    'GRIME',
    'ADVICE',
    3.30,
    '05-JAN-19',
    CURRENT_TIMESTAMP,
    'CADET',
    NULL,
    NULL
);
--SELECT STATEMENT FOR PART2
SELECT OWNER_NAME, EMAIL, CAR1, CAR1REG, CAR1CAP, CAR2, CAR2REG, CAR2CAP, CAR3, CAR3REG, CAR3CAP FROM CARS;

--PART 2 CREATE
CREATE TABLE CARS (
    OWNER_NAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(20) PRIMARY KEY,
    CAR1 VARCHAR(20) NULL,
    CAR1REG VARCHAR(20) NULL,
    CAR1CAP NUMBER(10) NULL,
    CAR2 VARCHAR(20) NULL,
    CAR2REG VARCHAR(20) NULL,
    CAR2CAP NUMBER(10) NULL,
    CAR3 VARCHAR(20) NULL,
    CAR3REG VARCHAR(20) NULL,
    CAR3CAP NUMBER(10) NULL
);

--PART 2 INSERT
INSERT INTO CARS VALUES (
    'KEN DELVIN',
    'KEN@DIT.IE',
    'TOYOTA LEXUS SILVER',
    '07D11211',
    6,
    'VOLKSWAGEN GOLF',
    '00D1831',
    NULL,
    'AUDI 100',
    '90D10800',
    NULL
);

INSERT INTO CARS VALUES (
    'FRED BLOGGS',
    'FRED@IBM.IE',
    'FORD ESCORT',
    '80D2002',
    5,
    'FORD ANGLIA',
    '50D03',
    4,
    NULL,
    NULL,
    NULL
);