--PART 1
DESCRIBE CKELLYSOC.HOTEL;

--PART 2
CREATE TABLE MY_HOTEL AS 
(SELECT HOTEL_NO, NAME, ADDRESS FROM CKELLYSOC.HOTEL);

--PART 3
SELECT HOTEL_NO, NAME, ADDRESS FROM MY_HOTEL;

--PART 4
ALTER TABLE MY_HOTEL ADD NIGHTLY_FEE NUMBER(32);

--PART 5
UPDATE MY_HOTEL
SET NIGHTLY_FEE =  150 
WHERE HOTEL_NO BETWEEN 0 AND 400;

--PART 6
ALTER TABLE MY_HOTEL ADD PRIMARY KEY(HOTEL_NO);

--PART 7 AND 8
CREATE TABLE MY_BOOKING (
    BOOKCODE NUMBER(8) PRIMARY KEY,
    START_DATE DATE,
    END_DATE DATE,
    HOTEL_NO NUMBER(6) NOT NULL REFERENCES MY_HOTEL
);

--PART 9
INSERT INTO MY_BOOKING VALUES (
    12345678,
    TO_DATE('01-01-2019', 'DD-MM-YYYY'),
    TO_DATE('05-01-2019', 'DD-MM-YYYY'),
    300
);

INSERT INTO MY_BOOKING VALUES (
    56710842,
    TO_DATE('05-03-2019', 'DD-MM-YYYY'),
    TO_DATE('11-03-2019', 'DD-MM-YYYY'),
    400
);

INSERT INTO MY_BOOKING VALUES (
    98150242,
    TO_DATE('23-04-2019', 'DD-MM-YYYY'),
    TO_DATE('25-04-2019', 'DD-MM-YYYY'),
    500
);

INSERT INTO MY_BOOKING VALUES (
    51094287,
    TO_DATE('31-05-2019', 'DD-MM-YYYY'),
    TO_DATE('05-06-2019', 'DD-MM-YYYY'),
    404
);

--SELECT STATEMENT TO SHOW INSERTS
SELECT BOOKCODE, START_DATE, END_DATE, HOTEL_NO FROM MY_BOOKING;

--PART 10
COMMIT;