--PART 1.1
SELECT COUNT(MTITLE) FROM MOVIES;

--PART 1.2
SELECT DISTINCT GENRE FROM MOVIES;

--PART 1.3
SELECT GENRE, COUNT(GENRE)
FROM MOVIES
GROUP BY GENRE;

--PART 1.4
SELECT DISTINCT GENRE, MIN(RUNNING_TIME), MAX(RUNNING_TIME)
FROM MOVIES
GROUP BY GENRE;

--PART 1.5
SELECT GENRE, COUNT(RUNNING_TIME)
FROM MOVIES
WHERE RUNNING_TIME BETWEEN 90 AND 180 GROUP BY GENRE;

--PART 1.6
SELECT GENRE, RATING, COUNT(MTITLE)
FROM MOVIES
GROUP BY GENRE, RATING;

--PART 1.7
SELECT RATING, AVG(BOX_OFFICE)
FROM MOVIES 
GROUP BY RATING
HAVING AVG(BOX_OFFICE) > 66;

--PART 2.1